メモアプリを作成しました
kei-kmj/VueToDo pull request #1
Opened 2022-05-28 08:50 UTC by kei-kmj

よろしくお願いします

2022-06-04 08:00 UTC, komagata requested changes

2022-06-04 08:00 UTC, komagata commented on todo.html
> +
不要な空行があるようです〜

2022-06-04 08:00 UTC, komagata commented on todo.html
> +
不要な空行があるようです〜

2022-06-16 02:18 UTC, kei-kmj reviewed
確認ありがとうございます。修正しました

2022-06-16 02:18 UTC, kei-kmj commented on todo.html
> +
削除しました

2022-06-16 02:18 UTC, kei-kmj commented on todo.html
> +
削除しました🙏

2022-06-17 07:22 UTC, komagata approved these changes
確認させて頂きました。OKです〜🙆‍♂️

2022-09-20 05:42 UTC, merged